# Neural Prototyping

# Google Colab Mounting

In [1]:
!rm -rf /content/credit-risk-modeling
!git clone https://github.com/BillyBrothers/credit-risk-modeling.git
!pip install -r /content/credit-risk-modeling/requirements.txt

import sys 
sys.path.append('/content/credit-risk-modeling')

Cloning into 'credit-risk-modeling'...
remote: Enumerating objects: 1249, done.
remote: Counting objects: 100% (128/128), done.Counting objects:  94% (121/128)
remote: Compressing objects: 100% (88/88), done.
remote: Total 1249 (delta 89), reused 79 (delta 40), pack-reused 1121 (from 1)
Receiving objects: 100% (1249/1249), 52.34 MiB | 24.19 MiB/s, done.
Resolving deltas: 100% (851/851), done.
Requirement already satisfied: feature_engine in /usr/local/lib/python3.12/dist-packages (from -r /content/credit-risk-modeling/requirements.txt (line 3)) (1.9.3)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from -r /content/credit-risk-modeling/requirements.txt (line 6)) (0.7.3)
Requirement already satisfied: pyampute in /usr/local/lib/python3.12/dist-packages (from -r /content/credit-risk-modeling/requirements.txt (line 9)) (0.0.3)
Requirement already satisfied: missingno in /usr/local/lib/python3.12/dist-packages (from -r /content/credit-risk-modeling/requirements.txt (line 10)) (0.5.2)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (0.14.6)
Requirement already satisfied: matplotlib>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from missingno->-r /content/credit-risk-modeling/requirements.txt (line 10)) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.11.1->feature_engine->-r /content/credit-risk-modeling/requirements.txt (line 3)) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.4.0->pyampute->-r /content/credit-risk-modeling/requirements.txt (line 9)) (1.17.0)

In [2]:
!pip install scikeras

Requirement already satisfied: scikeras in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikeras) (3.10.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras>=3.2.0->scikeras) (26.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)

In [3]:
pip install -q -U keras-tuner

In [4]:
# data analysis
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
import seaborn as sns
from pyampute.exploration.md_patterns import mdPatterns
from pyampute.exploration.mcar_statistical_tests import MCARTest
import missingno as msno

# preprocessing
import sklearn.utils.validation
import sys
from scipy import stats
from scipy.stats import shapiro, distributions, loguniform
from scipy.stats.mstats import winsorize
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import train_test_split, GridSearchCV, HalvingRandomSearchCV, HalvingGridSearchCV, TunedThresholdClassifierCV, FixedThresholdClassifier
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
from sklearn.preprocessing import StandardScaler, PowerTransformer, QuantileTransformer, MinMaxScaler, KBinsDiscretizer, Binarizer, PolynomialFeatures, LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from feature_engine.outliers import Winsorizer
from imblearn.over_sampling import SMOTE, SMOTENC
from sklearn.pipeline import Pipeline
from sklearn import set_config

# Feature Selection
from sklearn.feature_selection import SelectFromModel

# Modeling
from sklearn.linear_model import RidgeClassifier, LogisticRegression, RidgeClassifierCV, LogisticRegressionCV, SGDClassifier, Perceptron, PassiveAggressiveClassifier
from sklearn.svm import LinearSVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.dummy import DummyClassifier
import joblib

# Metrics
from sklearn.metrics import confusion_matrix, recall_score, precision_score, balanced_accuracy_score, ConfusionMatrixDisplay, classification_report, precision_recall_curve, PrecisionRecallDisplay, log_loss, brier_score_loss, roc_curve, roc_auc_score, RocCurveDisplay, det_curve, DetCurveDisplay, fbeta_score, average_precision_score, matthews_corrcoef

# Calibration
from sklearn.calibration import calibration_curve, CalibrationDisplay, CalibratedClassifierCV

# Inspection
from sklearn.inspection import PartialDependenceDisplay
from credit_risk_modeling import model_eval

import tensorflow as tf
from tensorflow import keras
from keras import layers
from scikeras.wrappers import KerasClassifier
import keras_tuner as kt

2026-02-06 20:47:16.001 | INFO     | credit_risk_modeling.config:<module>:11 - PROJ_ROOT path is: /content/credit-risk-modeling

In [5]:
!ls

credit-risk-modeling  logs  sample_data

In [6]:
!ls credit-risk-modeling

credit_risk_modeling  LICENSE	 pyproject.toml  requirements.txt
data		      Makefile	 README.md	 tests
docs		      models	 references
environment.yml       notebooks  reports

# Imports

In [7]:
X_train = pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/processed/X_train_neural.csv"
)

In [8]:
X_test = pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/processed/X_test_neural.csv"
)

In [9]:
X_val = pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/processed/X_val_neural.csv"
)

In [10]:
y_train= pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/interim/y_train.csv"
)
y_train = y_train.values.ravel()
neg, pos = np.bincount(y_train)
total = neg + pos
print(f"Examples:\n The training sets total amount of samples: {total}\n Positive: {pos} ({pos/total*100:.2f}% of total)")

Examples:
 The training sets total amount of samples: 22686
 Positive: 4962 (21.87% of total)

In [11]:
y_test = pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/interim/y_test.csv"
)
y_test = y_test.values.ravel()
neg, pos = np.bincount(y_test)
total = neg + pos
print(f"Examples:\n The testing set total amount of samples: {total}\n Positive: {pos} ({pos/total*100:.2f}% of total)")

Examples:
 The testing set total amount of samples: 2917
 Positive: 638 (21.87% of total)

In [12]:
y_val = pd.read_csv(
    filepath_or_buffer= "/content/credit-risk-modeling/data/interim/y_val.csv"
)
y_val = y_val.values.ravel()
neg, pos = np.bincount(y_val)
total = neg + pos
print(f"Examples:\n The validation set total amount of samples: {total}\n Positive: {pos} ({pos/total*100:.2f}% of total)")

Examples:
 The validation set total amount of samples: 6806
 Positive: 1488 (21.86% of total)

# Build Sequential Models

In [13]:
# # Architecture 1: Single hidden dense layer
def mlp1():
    model = keras.Sequential(name='MLP-1')
    model.add(keras.Input(shape=(X_train.shape[1], ))),
    model.add(layers.Dense(units=64, activation='relu')),
    model.add(layers.Dropout(rate= 0.20)),
    model.add(layers.Dense(units=1,activation='sigmoid')),
    model.compile(
        optimizer= keras.optimizers.Adam(),
        loss= keras.losses.BinaryCrossentropy(),
        metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
)
    return model

In [14]:
# def mlp1(hp):
#     model1 = keras.Sequential(name='MLP-1')
#     model1.add(keras.Input(shape=(X_train.shape[1], )))

#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     hp_lr = hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='log')

#     model1.add(layers.Dense(units=hp_units, activation='relu'))
#     model1.add(layers.Dropout(rate= 0.20))
#     model1.add(layers.Dense(units=1,activation='sigmoid'))
    
#     model1.compile(optimizer=keras.optimizers.Adam(learning_rate=hp_lr),
#                 loss=keras.losses.BinaryCrossentropy(),
#                 metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
#     ) 
#     return model1

In [15]:
# Architecture 2: Two hidden dense layers
def mlp2():
    model = keras.Sequential(name='MLP-2')
    model.add(keras.Input(shape=(X_train.shape[1], ))),
    model.add(layers.Dense(units=64, activation='relu')),
    model.add(layers.Dropout(rate= 0.20)),
    model.add(layers.Dense(units=128, activation='relu')),
    model.add(layers.Dropout(rate=0.20)),
    model.add(layers.Dense(units=1,activation='sigmoid')),
    
    model.compile(optimizer=keras.optimizers.Adam(),
                loss=keras.losses.BinaryCrossentropy(),
                metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
    )
    return model

In [16]:
# # Architecture 2: Two hidden dense layers
# def mlp2(hp):
#     model2 = keras.Sequential(name='MLP-2')
#     model2.add(keras.Input(shape=(X_train.shape[1], ))),
#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     model2.add(layers.Dense(units=hp_units, activation='relu')),
#     model2.add(layers.Dropout(rate= 0.20)),
#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     model2.add(layers.Dense(units=hp_units, activation='relu')),
#     model2.add(layers.Dropout(rate=0.20)),
#     model2.add(layers.Dense(units=1,activation='sigmoid')),
#     model2.compile(optimizer=keras.optimizers.Adam(),
#                 loss=keras.losses.BinaryCrossentropy(),
#                 metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
#     )
#     return model2

In [17]:
# Architecture 3: Three hidden dense layers
def mlp3():
    model = keras.Sequential(name='MLP-3')
    model.add(keras.Input(shape=(X_train.shape[1], ))),
    model.add(layers.Dense(units=64, activation='relu')),
    model.add(layers.Dropout(rate= 0.20)),
    model.add(layers.Dense(units=128, activation='relu')),
    model.add(layers.Dropout(rate=0.20)),
    model.add(layers.Dense(units=256, activation='relu')),
    model.add(layers.Dropout(rate=0.2)),
    model.add(layers.Dense(units=1,activation='sigmoid')),

    model.compile(
        optimizer= keras.optimizers.Adam(),
        loss= keras.losses.BinaryCrossentropy(),
        metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
)
    return model

In [18]:
# def mlp3(hp):
#     model3 = keras.Sequential(name='MLP-3')
#     model3.add(keras.Input(shape=(X_train.shape[1], ))),
#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     model3.add(layers.Dense(units=hp_units, activation='relu')),
#     model3.add(layers.Dropout(rate= 0.20)),
#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     model3.add(layers.Dense(units=hp_units, activation='relu')),
#     model3.add(layers.Dropout(rate=0.20)),
#     hp_units= hp.Int('units', min_value=64, max_value=512, step=32)
#     model3.add(layers.Dense(units=hp_units, activation='relu')),
#     model3.add(layers.Dropout(rate=0.2)),
#     model3.add(layers.Dense(units=1,activation='sigmoid')),
#     model3.compile(optimizer=keras.optimizers.Adam(),
#                 loss=keras.losses.BinaryCrossentropy(),
#                 metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
#     )

#     return model3

In [19]:
mlp_models = [
    ("MLP-1", mlp1()),
    ("MLP-2", mlp2()),
    ("MLP-3", mlp3())
]

### Callbacks

In [20]:
reduce_lr_plateau = keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.2,
    patience=3,
    verbose=1,
    min_lr=0.001
)

In [21]:
early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=1e-4,
    patience=7,
    verbose=1,
    restore_best_weights=True
)

In [22]:
log_dir = "logs/fit/"
tensorboard = keras.callbacks.TensorBoard(
    log_dir= log_dir
)

### Fit

In [23]:
class_weight = {
    0: 1.0,
    1: 2.0
    }

In [24]:
histories = {}

In [25]:
for model_name, model in mlp_models:
    print(f"Currently fitting model {model_name}.")
    history = model.fit(
        x= X_train,
        y= y_train,
        batch_size=32,
        epochs= 100,
        verbose=2,
        callbacks= [early_stopping, reduce_lr_plateau, tensorboard],
        validation_data= (X_val, y_val),
        class_weight= class_weight
    )
    histories[model_name] = history.history

Currently fitting model MLP-1.
Epoch 1/100
709/709 - 3s - 4ms/step - auc: 0.8525 - loss: 0.5503 - val_auc: 0.8906 - val_loss: 0.3473 - learning_rate: 1.0000e-03
Epoch 2/100
709/709 - 1s - 2ms/step - auc: 0.8873 - loss: 0.4820 - val_auc: 0.9003 - val_loss: 0.3235 - learning_rate: 1.0000e-03
Epoch 3/100
709/709 - 1s - 2ms/step - auc: 0.8956 - loss: 0.4620 - val_auc: 0.9053 - val_loss: 0.3261 - learning_rate: 1.0000e-03
Epoch 4/100
709/709 - 1s - 2ms/step - auc: 0.8996 - loss: 0.4514 - val_auc: 0.9080 - val_loss: 0.3062 - learning_rate: 1.0000e-03
Epoch 5/100
709/709 - 1s - 2ms/step - auc: 0.9025 - loss: 0.4423 - val_auc: 0.9085 - val_loss: 0.2993 - learning_rate: 1.0000e-03
Epoch 6/100
709/709 - 1s - 2ms/step - auc: 0.9050 - loss: 0.4352 - val_auc: 0.9101 - val_loss: 0.2906 - learning_rate: 1.0000e-03
Epoch 7/100
709/709 - 1s - 2ms/step - auc: 0.9051 - loss: 0.4330 - val_auc: 0.9130 - val_loss: 0.2897 - learning_rate: 1.0000e-03
Epoch 8/100
709/709 - 2s - 3ms/step - auc: 0.9086 - loss: 0.4241 - val_auc: 0.9129 - val_loss: 0.2896 - learning_rate: 1.0000e-03
Epoch 9/100
709/709 - 2s - 3ms/step - auc: 0.9075 - loss: 0.4244 - val_auc: 0.9135 - val_loss: 0.2962 - learning_rate: 1.0000e-03
Epoch 10/100
709/709 - 1s - 2ms/step - auc: 0.9098 - loss: 0.4184 - val_auc: 0.9145 - val_loss: 0.2843 - learning_rate: 1.0000e-03
Epoch 11/100
709/709 - 1s - 2ms/step - auc: 0.9104 - loss: 0.4161 - val_auc: 0.9154 - val_loss: 0.2822 - learning_rate: 1.0000e-03
Epoch 12/100
709/709 - 1s - 2ms/step - auc: 0.9121 - loss: 0.4113 - val_auc: 0.9165 - val_loss: 0.2803 - learning_rate: 1.0000e-03
Epoch 13/100
709/709 - 1s - 2ms/step - auc: 0.9128 - loss: 0.4088 - val_auc: 0.9171 - val_loss: 0.2805 - learning_rate: 1.0000e-03
Epoch 14/100
709/709 - 1s - 2ms/step - auc: 0.9141 - loss: 0.4052 - val_auc: 0.9176 - val_loss: 0.2787 - learning_rate: 1.0000e-03
Epoch 15/100
709/709 - 2s - 3ms/step - auc: 0.9143 - loss: 0.4024 - val_auc: 0.9191 - val_loss: 0.2714 - learning_rate: 1.0000e-03
Epoch 16/100
709/709 - 1s - 2ms/step - auc: 0.9147 - loss: 0.4007 - val_auc: 0.9187 - val_loss: 0.2786 - learning_rate: 1.0000e-03
Epoch 17/100
709/709 - 1s - 2ms/step - auc: 0.9160 - loss: 0.3976 - val_auc: 0.9184 - val_loss: 0.2690 - learning_rate: 1.0000e-03
Epoch 18/100
709/709 - 1s - 2ms/step - auc: 0.9163 - loss: 0.3955 - val_auc: 0.9196 - val_loss: 0.2733 - learning_rate: 1.0000e-03
Epoch 19/100
709/709 - 2s - 2ms/step - auc: 0.9172 - loss: 0.3937 - val_auc: 0.9198 - val_loss: 0.2720 - learning_rate: 1.0000e-03
Epoch 20/100
709/709 - 2s - 2ms/step - auc: 0.9172 - loss: 0.3922 - val_auc: 0.9208 - val_loss: 0.2615 - learning_rate: 1.0000e-03
Epoch 21/100
709/709 - 1s - 2ms/step - auc: 0.9180 - loss: 0.3893 - val_auc: 0.9202 - val_loss: 0.2660 - learning_rate: 1.0000e-03
Epoch 22/100
709/709 - 2s - 3ms/step - auc: 0.9172 - loss: 0.3911 - val_auc: 0.9198 - val_loss: 0.2696 - learning_rate: 1.0000e-03
Epoch 23/100
709/709 - 2s - 2ms/step - auc: 0.9186 - loss: 0.3870 - val_auc: 0.9209 - val_loss: 0.2625 - learning_rate: 1.0000e-03
Epoch 24/100
709/709 - 2s - 2ms/step - auc: 0.9196 - loss: 0.3842 - val_auc: 0.9224 - val_loss: 0.2630 - learning_rate: 1.0000e-03
Epoch 25/100
709/709 - 2s - 2ms/step - auc: 0.9195 - loss: 0.3853 - val_auc: 0.9228 - val_loss: 0.2613 - learning_rate: 1.0000e-03
Epoch 26/100
709/709 - 2s - 2ms/step - auc: 0.9189 - loss: 0.3854 - val_auc: 0.9224 - val_loss: 0.2637 - learning_rate: 1.0000e-03
Epoch 27/100
709/709 - 2s - 2ms/step - auc: 0.9199 - loss: 0.3819 - val_auc: 0.9230 - val_loss: 0.2585 - learning_rate: 1.0000e-03
Epoch 28/100
709/709 - 2s - 2ms/step - auc: 0.9205 - loss: 0.3800 - val_auc: 0.9231 - val_loss: 0.2595 - learning_rate: 1.0000e-03
Epoch 29/100
709/709 - 2s - 3ms/step - auc: 0.9217 - loss: 0.3776 - val_auc: 0.9228 - val_loss: 0.2605 - learning_rate: 1.0000e-03
Epoch 30/100
709/709 - 2s - 2ms/step - auc: 0.9220 - loss: 0.3771 - val_auc: 0.9223 - val_loss: 0.2579 - learning_rate: 1.0000e-03
Epoch 31/100
709/709 - 1s - 2ms/step - auc: 0.9220 - loss: 0.3762 - val_auc: 0.9234 - val_loss: 0.2591 - learning_rate: 1.0000e-03
Epoch 32/100
709/709 - 2s - 2ms/step - auc: 0.9224 - loss: 0.3747 - val_auc: 0.9232 - val_loss: 0.2559 - learning_rate: 1.0000e-03
Epoch 33/100
709/709 - 2s - 3ms/step - auc: 0.9222 - loss: 0.3756 - val_auc: 0.9239 - val_loss: 0.2565 - learning_rate: 1.0000e-03
Epoch 34/100
709/709 - 1s - 2ms/step - auc: 0.9227 - loss: 0.3715 - val_auc: 0.9234 - val_loss: 0.2605 - learning_rate: 1.0000e-03
Epoch 35/100
709/709 - 1s - 2ms/step - auc: 0.9224 - loss: 0.3731 - val_auc: 0.9234 - val_loss: 0.2590 - learning_rate: 1.0000e-03
Epoch 36/100
709/709 - 2s - 3ms/step - auc: 0.9231 - loss: 0.3724 - val_auc: 0.9234 - val_loss: 0.2563 - learning_rate: 1.0000e-03
Epoch 37/100
709/709 - 1s - 2ms/step - auc: 0.9233 - loss: 0.3720 - val_auc: 0.9235 - val_loss: 0.2519 - learning_rate: 1.0000e-03
Epoch 38/100
709/709 - 2s - 2ms/step - auc: 0.9237 - loss: 0.3703 - val_auc: 0.9245 - val_loss: 0.2560 - learning_rate: 1.0000e-03
Epoch 39/100
709/709 - 1s - 2ms/step - auc: 0.9222 - loss: 0.3727 - val_auc: 0.9244 - val_loss: 0.2533 - learning_rate: 1.0000e-03
Epoch 40/100
709/709 - 1s - 2ms/step - auc: 0.9241 - loss: 0.3696 - val_auc: 0.9242 - val_loss: 0.2610 - learning_rate: 1.0000e-03
Epoch 41/100
709/709 - 1s - 2ms/step - auc: 0.9239 - loss: 0.3697 - val_auc: 0.9241 - val_loss: 0.2586 - learning_rate: 1.0000e-03
Epoch 42/100
709/709 - 3s - 4ms/step - auc: 0.9236 - loss: 0.3697 - val_auc: 0.9234 - val_loss: 0.2547 - learning_rate: 1.0000e-03
Epoch 43/100
709/709 - 1s - 2ms/step - auc: 0.9231 - loss: 0.3695 - val_auc: 0.9233 - val_loss: 0.2568 - learning_rate: 1.0000e-03
Epoch 44/100
709/709 - 1s - 2ms/step - auc: 0.9237 - loss: 0.3690 - val_auc: 0.9234 - val_loss: 0.2526 - learning_rate: 1.0000e-03
Epoch 44: early stopping
Restoring model weights from the end of the best epoch: 37.
Currently fitting model MLP-2.
Epoch 1/100
709/709 - 3s - 4ms/step - auc: 0.8610 - loss: 0.5324 - val_auc: 0.9010 - val_loss: 0.3368 - learning_rate: 1.0000e-03
Epoch 2/100
709/709 - 2s - 2ms/step - auc: 0.8908 - loss: 0.4675 - val_auc: 0.9118 - val_loss: 0.2962 - learning_rate: 1.0000e-03
Epoch 3/100
709/709 - 3s - 4ms/step - auc: 0.9030 - loss: 0.4353 - val_auc: 0.9177 - val_loss: 0.2740 - learning_rate: 1.0000e-03
Epoch 4/100
709/709 - 2s - 3ms/step - auc: 0.9077 - loss: 0.4186 - val_auc: 0.9192 - val_loss: 0.2608 - learning_rate: 1.0000e-03
Epoch 5/100
709/709 - 2s - 3ms/step - auc: 0.9110 - loss: 0.4067 - val_auc: 0.9216 - val_loss: 0.2566 - learning_rate: 1.0000e-03
Epoch 6/100
709/709 - 2s - 2ms/step - auc: 0.9145 - loss: 0.3985 - val_auc: 0.9224 - val_loss: 0.2567 - learning_rate: 1.0000e-03
Epoch 7/100
709/709 - 2s - 2ms/step - auc: 0.9177 - loss: 0.3881 - val_auc: 0.9233 - val_loss: 0.2597 - learning_rate: 1.0000e-03
Epoch 8/100
709/709 - 2s - 2ms/step - auc: 0.9162 - loss: 0.3897 - val_auc: 0.9227 - val_loss: 0.2502 - learning_rate: 1.0000e-03
Epoch 9/100
709/709 - 2s - 2ms/step - auc: 0.9189 - loss: 0.3800 - val_auc: 0.9233 - val_loss: 0.2516 - learning_rate: 1.0000e-03
Epoch 10/100
709/709 - 2s - 3ms/step - auc: 0.9197 - loss: 0.3771 - val_auc: 0.9236 - val_loss: 0.2506 - learning_rate: 1.0000e-03
Epoch 11/100
709/709 - 2s - 2ms/step - auc: 0.9208 - loss: 0.3727 - val_auc: 0.9242 - val_loss: 0.2516 - learning_rate: 1.0000e-03
Epoch 12/100
709/709 - 2s - 2ms/step - auc: 0.9212 - loss: 0.3724 - val_auc: 0.9225 - val_loss: 0.2692 - learning_rate: 1.0000e-03
Epoch 13/100
709/709 - 2s - 2ms/step - auc: 0.9213 - loss: 0.3717 - val_auc: 0.9236 - val_loss: 0.2532 - learning_rate: 1.0000e-03
Epoch 14/100
709/709 - 2s - 2ms/step - auc: 0.9232 - loss: 0.3656 - val_auc: 0.9238 - val_loss: 0.2443 - learning_rate: 1.0000e-03
Epoch 15/100
709/709 - 2s - 2ms/step - auc: 0.9227 - loss: 0.3664 - val_auc: 0.9239 - val_loss: 0.2521 - learning_rate: 1.0000e-03
Epoch 16/100
709/709 - 2s - 2ms/step - auc: 0.9251 - loss: 0.3605 - val_auc: 0.9233 - val_loss: 0.2445 - learning_rate: 1.0000e-03
Epoch 17/100
709/709 - 2s - 3ms/step - auc: 0.9250 - loss: 0.3601 - val_auc: 0.9234 - val_loss: 0.2449 - learning_rate: 1.0000e-03
Epoch 18/100
709/709 - 2s - 2ms/step - auc: 0.9259 - loss: 0.3592 - val_auc: 0.9244 - val_loss: 0.2371 - learning_rate: 1.0000e-03
Epoch 19/100
709/709 - 2s - 2ms/step - auc: 0.9249 - loss: 0.3580 - val_auc: 0.9250 - val_loss: 0.2416 - learning_rate: 1.0000e-03
Epoch 20/100
709/709 - 2s - 2ms/step - auc: 0.9262 - loss: 0.3575 - val_auc: 0.9240 - val_loss: 0.2373 - learning_rate: 1.0000e-03
Epoch 21/100
709/709 - 2s - 2ms/step - auc: 0.9272 - loss: 0.3529 - val_auc: 0.9248 - val_loss: 0.2371 - learning_rate: 1.0000e-03
Epoch 22/100
709/709 - 2s - 2ms/step - auc: 0.9259 - loss: 0.3547 - val_auc: 0.9251 - val_loss: 0.2327 - learning_rate: 1.0000e-03
Epoch 23/100
709/709 - 2s - 3ms/step - auc: 0.9281 - loss: 0.3507 - val_auc: 0.9257 - val_loss: 0.2282 - learning_rate: 1.0000e-03
Epoch 24/100
709/709 - 2s - 3ms/step - auc: 0.9268 - loss: 0.3520 - val_auc: 0.9253 - val_loss: 0.2420 - learning_rate: 1.0000e-03
Epoch 25/100
709/709 - 2s - 2ms/step - auc: 0.9277 - loss: 0.3492 - val_auc: 0.9236 - val_loss: 0.2429 - learning_rate: 1.0000e-03
Epoch 26/100
709/709 - 2s - 2ms/step - auc: 0.9279 - loss: 0.3495 - val_auc: 0.9248 - val_loss: 0.2431 - learning_rate: 1.0000e-03
Epoch 27/100
709/709 - 2s - 2ms/step - auc: 0.9282 - loss: 0.3480 - val_auc: 0.9221 - val_loss: 0.2482 - learning_rate: 1.0000e-03
Epoch 28/100
709/709 - 2s - 2ms/step - auc: 0.9290 - loss: 0.3491 - val_auc: 0.9247 - val_loss: 0.2427 - learning_rate: 1.0000e-03
Epoch 29/100
709/709 - 2s - 2ms/step - auc: 0.9284 - loss: 0.3469 - val_auc: 0.9236 - val_loss: 0.2528 - learning_rate: 1.0000e-03
Epoch 30/100
709/709 - 2s - 3ms/step - auc: 0.9292 - loss: 0.3461 - val_auc: 0.9231 - val_loss: 0.2434 - learning_rate: 1.0000e-03
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 23.
Currently fitting model MLP-3.
Epoch 1/100
709/709 - 3s - 5ms/step - auc: 0.8646 - loss: 0.5251 - val_auc: 0.9070 - val_loss: 0.3071 - learning_rate: 1.0000e-03
Epoch 2/100
709/709 - 2s - 3ms/step - auc: 0.8957 - loss: 0.4537 - val_auc: 0.9123 - val_loss: 0.2823 - learning_rate: 1.0000e-03
Epoch 3/100
709/709 - 3s - 4ms/step - auc: 0.9021 - loss: 0.4341 - val_auc: 0.9193 - val_loss: 0.2854 - learning_rate: 1.0000e-03
Epoch 4/100
709/709 - 2s - 3ms/step - auc: 0.9086 - loss: 0.4131 - val_auc: 0.9206 - val_loss: 0.2817 - learning_rate: 1.0000e-03
Epoch 5/100
709/709 - 2s - 3ms/step - auc: 0.9120 - loss: 0.4028 - val_auc: 0.9222 - val_loss: 0.2565 - learning_rate: 1.0000e-03
Epoch 6/100
709/709 - 2s - 3ms/step - auc: 0.9136 - loss: 0.3975 - val_auc: 0.9233 - val_loss: 0.2526 - learning_rate: 1.0000e-03
Epoch 7/100
709/709 - 2s - 3ms/step - auc: 0.9164 - loss: 0.3880 - val_auc: 0.9223 - val_loss: 0.2654 - learning_rate: 1.0000e-03
Epoch 8/100
709/709 - 2s - 3ms/step - auc: 0.9163 - loss: 0.3839 - val_auc: 0.9258 - val_loss: 0.2537 - learning_rate: 1.0000e-03
Epoch 9/100
709/709 - 3s - 4ms/step - auc: 0.9186 - loss: 0.3772 - val_auc: 0.9232 - val_loss: 0.2478 - learning_rate: 1.0000e-03
Epoch 10/100
709/709 - 2s - 3ms/step - auc: 0.9185 - loss: 0.3778 - val_auc: 0.9246 - val_loss: 0.2419 - learning_rate: 1.0000e-03
Epoch 11/100
709/709 - 2s - 3ms/step - auc: 0.9197 - loss: 0.3751 - val_auc: 0.9218 - val_loss: 0.2578 - learning_rate: 1.0000e-03
Epoch 12/100
709/709 - 2s - 3ms/step - auc: 0.9194 - loss: 0.3720 - val_auc: 0.9227 - val_loss: 0.2546 - learning_rate: 1.0000e-03
Epoch 13/100
709/709 - 2s - 3ms/step - auc: 0.9221 - loss: 0.3666 - val_auc: 0.9246 - val_loss: 0.2410 - learning_rate: 1.0000e-03
Epoch 14/100
709/709 - 2s - 3ms/step - auc: 0.9221 - loss: 0.3664 - val_auc: 0.9230 - val_loss: 0.2482 - learning_rate: 1.0000e-03
Epoch 15/100
709/709 - 2s - 3ms/step - auc: 0.9227 - loss: 0.3625 - val_auc: 0.9246 - val_loss: 0.2415 - learning_rate: 1.0000e-03
Epoch 16/100
709/709 - 2s - 3ms/step - auc: 0.9231 - loss: 0.3641 - val_auc: 0.9241 - val_loss: 0.2466 - learning_rate: 1.0000e-03
Epoch 17/100
709/709 - 2s - 3ms/step - auc: 0.9235 - loss: 0.3617 - val_auc: 0.9237 - val_loss: 0.2449 - learning_rate: 1.0000e-03
Epoch 18/100
709/709 - 2s - 3ms/step - auc: 0.9256 - loss: 0.3574 - val_auc: 0.9233 - val_loss: 0.2642 - learning_rate: 1.0000e-03
Epoch 19/100
709/709 - 2s - 3ms/step - auc: 0.9241 - loss: 0.3589 - val_auc: 0.9240 - val_loss: 0.2431 - learning_rate: 1.0000e-03
Epoch 20/100
709/709 - 2s - 3ms/step - auc: 0.9256 - loss: 0.3567 - val_auc: 0.9216 - val_loss: 0.2392 - learning_rate: 1.0000e-03
Epoch 21/100
709/709 - 2s - 3ms/step - auc: 0.9267 - loss: 0.3527 - val_auc: 0.9249 - val_loss: 0.2416 - learning_rate: 1.0000e-03
Epoch 22/100
709/709 - 2s - 3ms/step - auc: 0.9262 - loss: 0.3549 - val_auc: 0.9258 - val_loss: 0.2340 - learning_rate: 1.0000e-03
Epoch 23/100
709/709 - 2s - 3ms/step - auc: 0.9265 - loss: 0.3509 - val_auc: 0.9242 - val_loss: 0.2284 - learning_rate: 1.0000e-03
Epoch 24/100
709/709 - 2s - 3ms/step - auc: 0.9264 - loss: 0.3517 - val_auc: 0.9230 - val_loss: 0.2386 - learning_rate: 1.0000e-03
Epoch 25/100
709/709 - 3s - 4ms/step - auc: 0.9261 - loss: 0.3534 - val_auc: 0.9247 - val_loss: 0.2446 - learning_rate: 1.0000e-03
Epoch 26/100
709/709 - 2s - 3ms/step - auc: 0.9270 - loss: 0.3501 - val_auc: 0.9232 - val_loss: 0.2382 - learning_rate: 1.0000e-03
Epoch 27/100
709/709 - 2s - 3ms/step - auc: 0.9260 - loss: 0.3514 - val_auc: 0.9264 - val_loss: 0.2405 - learning_rate: 1.0000e-03
Epoch 28/100
709/709 - 2s - 3ms/step - auc: 0.9293 - loss: 0.3450 - val_auc: 0.9257 - val_loss: 0.2236 - learning_rate: 1.0000e-03
Epoch 29/100
709/709 - 2s - 3ms/step - auc: 0.9282 - loss: 0.3492 - val_auc: 0.9254 - val_loss: 0.2449 - learning_rate: 1.0000e-03
Epoch 30/100
709/709 - 2s - 3ms/step - auc: 0.9285 - loss: 0.3456 - val_auc: 0.9236 - val_loss: 0.2456 - learning_rate: 1.0000e-03
Epoch 31/100
709/709 - 3s - 4ms/step - auc: 0.9291 - loss: 0.3464 - val_auc: 0.9235 - val_loss: 0.2368 - learning_rate: 1.0000e-03
Epoch 32/100
709/709 - 2s - 3ms/step - auc: 0.9293 - loss: 0.3456 - val_auc: 0.9254 - val_loss: 0.2346 - learning_rate: 1.0000e-03
Epoch 33/100
709/709 - 2s - 3ms/step - auc: 0.9307 - loss: 0.3419 - val_auc: 0.9229 - val_loss: 0.2365 - learning_rate: 1.0000e-03
Epoch 34/100
709/709 - 2s - 3ms/step - auc: 0.9293 - loss: 0.3448 - val_auc: 0.9249 - val_loss: 0.2312 - learning_rate: 1.0000e-03
Epoch 35/100
709/709 - 2s - 3ms/step - auc: 0.9305 - loss: 0.3434 - val_auc: 0.9234 - val_loss: 0.2417 - learning_rate: 1.0000e-03
Epoch 35: early stopping
Restoring model weights from the end of the best epoch: 28.

In [26]:
chosen_metric = 'val_auc'
max_auc_per_model = {}
best_auc = None
best_model = None
best_model_name = None

for model_name, model in mlp_models:
    max_auc_per_model[model_name] = max(histories[model_name][chosen_metric])
    max_auc_dict = dict([sorted(max_auc_per_model.items(), key= lambda item: item[1])[-1]])
    max_auc_model_name = list(max_auc_dict.keys())[0]
    max_aux_score = list(max_auc_dict.values())[0]
    if max_auc_model_name == model_name:
        best_auc = max_aux_score
        best_model_name = max_auc_model_name
        best_model = model
    else:
        continue

print(f"Results: \nBest model: {best_model_name}\nAUC score: {best_auc:.4f}")

Results:
Best model: MLP-3
AUC score: 0.9264

In [27]:
best_model.summary()

Model: "MLP-3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 64)             │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 256)            │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │           257 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 128,645 (502.52 KB)

 Trainable params: 42,881 (167.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 85,764 (335.02 KB)

### Hyperparameter Tuning

In [28]:
# for tid, t in tuner.oracle.trials.items():
#     print(tid, t.status, t.score)

In [29]:
# def mlp2_tuned(hp):
#     model = keras.Sequential(name='MLP-2-tuned')

#     units = hp.Int("units", 64, 256, step=32)
#     lr = hp.Float("learning_rate", 1e-4, 1e-2, sampling="log")

#     model.add(keras.Input(shape=(X_train.shape[1], ))),
#     model.add(layers.Dense(units=units, activation='relu')),
#     model.add(layers.Dropout(rate= 0.20)),
#     model.add(layers.Dense(units=units, activation='relu')),
#     model.add(layers.Dropout(rate=0.20)),
#     model.add(layers.Dense(units=1,activation='sigmoid')),
    
#     model.compile(optimizer=keras.optimizers.Adam(learning_rate=lr),
#                 loss=keras.losses.BinaryCrossentropy(),
#                 metrics= [keras.metrics.AUC(curve="ROC", name="auc")]
#     )
#     return model

In [30]:
# import shutil
# shutil.rmtree("untitled_project", ignore_errors=True)

In [31]:
# tuner = kt.Hyperband(
#     hypermodel= mlp2_tuned,
#     objective="val_auc",
#     max_epochs= 50,
#     factor=3,
# )

In [32]:
# tuner.search_space_summary()

In [33]:
# tuner.search(
#     X_train,
#     y_train,
#     validation_data= (X_val, y_val),
#     callbacks= [early_stopping]
# )

In [34]:
# tuner.results_summary()

### Calibration

Scikeras cannot accept an instance of a model only a user building function (factory function). So, my model will have NO weights on it.

In [35]:
models_only = {}
mlp_functions = []

In [36]:
for model_name, model in mlp_models:
    models_only[model_name] = KerasClassifier(
    model= model,
    optimizer= keras.optimizers.Adam(),
    loss= keras.losses.BinaryCrossentropy(),
    random_state=42,
    class_weight= class_weight,
    metrics= ['val_auc'],
    callbacks= [early_stopping, reduce_lr_plateau],
    validation_split= 0.20,
    epochs=100
)

In [37]:
for model_name, model in list(models_only.items()):
    mlp_functions.append(model)

In [38]:
models_performances, fitted_models = model_eval.comparing_models(
    mlp_functions,
    X_train,
    y_train,
    X_test,
    y_test
)

Epoch 1/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9213 - loss: 0.3694 - val_auc: 0.9282 - val_loss: 0.3651 - learning_rate: 0.0010
Epoch 2/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9225 - loss: 0.3650 - val_auc: 0.9274 - val_loss: 0.3664 - learning_rate: 0.0010
Epoch 3/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9204 - loss: 0.3656 - val_auc: 0.9266 - val_loss: 0.3677 - learning_rate: 0.0010
Epoch 4/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9220 - loss: 0.3657 - val_auc: 0.9262 - val_loss: 0.3691 - learning_rate: 0.0010
Epoch 5/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9208 - loss: 0.3662 - val_auc: 0.9256 - val_loss: 0.3691 - learning_rate: 0.0010
Epoch 6/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9221 - loss: 0.3640 - val_auc: 0.9256 - val_loss: 0.3695 - learning_rate: 0.0010
Epoch 7/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9233 - loss: 0.3633 - val_auc: 0.9252 - val_loss: 0.3703 - learning_rate: 0.0010
Epoch 8/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9229 - loss: 0.3640 - val_auc: 0.9251 - val_loss: 0.3705 - learning_rate: 0.0010
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 1.
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step
Epoch 1/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - auc: 0.9262 - loss: 0.3470 - val_auc: 0.9327 - val_loss: 0.3441 - learning_rate: 0.0010
Epoch 2/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9256 - loss: 0.3467 - val_auc: 0.9306 - val_loss: 0.3488 - learning_rate: 0.0010
Epoch 3/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9260 - loss: 0.3466 - val_auc: 0.9309 - val_loss: 0.3495 - learning_rate: 0.0010
Epoch 4/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9282 - loss: 0.3416 - val_auc: 0.9295 - val_loss: 0.3493 - learning_rate: 0.0010
Epoch 5/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9263 - loss: 0.3484 - val_auc: 0.9293 - val_loss: 0.3508 - learning_rate: 0.0010
Epoch 6/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9283 - loss: 0.3419 - val_auc: 0.9297 - val_loss: 0.3503 - learning_rate: 0.0010
Epoch 7/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9297 - loss: 0.3425 - val_auc: 0.9282 - val_loss: 0.3521 - learning_rate: 0.0010
Epoch 8/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - auc: 0.9297 - loss: 0.3381 - val_auc: 0.9275 - val_loss: 0.3543 - learning_rate: 0.0010
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 1.
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step
Epoch 1/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - auc: 0.9276 - loss: 0.3407 - val_auc: 0.9368 - val_loss: 0.3386 - learning_rate: 0.0010
Epoch 2/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9267 - loss: 0.3446 - val_auc: 0.9351 - val_loss: 0.3425 - learning_rate: 0.0010
Epoch 3/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9276 - loss: 0.3421 - val_auc: 0.9340 - val_loss: 0.3430 - learning_rate: 0.0010
Epoch 4/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9277 - loss: 0.3408 - val_auc: 0.9338 - val_loss: 0.3423 - learning_rate: 0.0010
Epoch 5/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9265 - loss: 0.3444 - val_auc: 0.9325 - val_loss: 0.3419 - learning_rate: 0.0010
Epoch 6/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9287 - loss: 0.3369 - val_auc: 0.9319 - val_loss: 0.3450 - learning_rate: 0.0010
Epoch 7/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9294 - loss: 0.3389 - val_auc: 0.9310 - val_loss: 0.3443 - learning_rate: 0.0010
Epoch 8/100
568/568 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - auc: 0.9287 - loss: 0.3416 - val_auc: 0.9312 - val_loss: 0.3434 - learning_rate: 0.0010
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 1.
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step

In [39]:
models_performances

,model,roc_auc,pr_auc,log_loss,brier_score,matthews_corrcoef
2,"MLP-3 (class_weight={0: 1.0, 1: 2.0})",0.921263,0.858739,0.250236,0.072312,0.740493
1,"MLP-2 (class_weight={0: 1.0, 1: 2.0})",0.920354,0.855507,0.252407,0.073342,0.730932
0,"MLP-1 (class_weight={0: 1.0, 1: 2.0})",0.916564,0.847145,0.271362,0.079895,0.707154

In [40]:
roc_auc = models_performances.loc[:,'roc_auc']

In [41]:
clean_functions = {"mlp1": mlp1(), 
 "mlp2": mlp2(), 
 "mlp3": mlp3()},

In [42]:
clean_functions_df = pd.DataFrame(
    data= clean_functions,
    index= range(0,1)
)

In [43]:
clean_functions_df = pd.melt(
    frame=clean_functions_df,
    value_vars= list(clean_functions_df.columns),
    var_name= 'MLP',
    value_name= 'model'
)

In [44]:
clean_functions_df

    MLP                                model
0  mlp1  <Sequential name=MLP-1, built=True>
1  mlp2  <Sequential name=MLP-2, built=True>
2  mlp3  <Sequential name=MLP-3, built=True>

In [45]:
clean_functions_df = pd.concat(
    objs= [clean_functions_df, roc_auc],
    axis=1
)

In [46]:
clean_functions_df.sort_values(
    by= 'roc_auc',
    axis=0,
    ascending=False,
    inplace= True
)

In [47]:
clean_functions_df.iloc[0]['model'].layers

[<Dense name=dense_14, built=True>,
 <Dropout name=dropout_9, built=True>,
 <Dense name=dense_15, built=True>,
 <Dropout name=dropout_10, built=True>,
 <Dense name=dense_16, built=True>,
 <Dropout name=dropout_11, built=True>,
 <Dense name=dense_17, built=True>]

In [48]:
class_weight

{0: 1.0, 1: 2.0}

In [49]:
top_performing_calibrated_models = model_eval.evaluate_calibration(
    clean_functions_df,
    fitted_models,
    X_train,
    y_train,
    X_test, 
    y_test
)

NameError: name 'class_weight' is not defined

In [ ]:
top_model_name = models_performances.iloc[0]['model']
top_performing_model = fitted_models[top_model_name]
methods = ['sigmoid', 'isotonic']

calibrated_models = {}   # store models here

# fig, ax = plt.subplots(figsize=(8,6))

for method in methods:
    # Fit calibrated model
    calibrated_model = CalibratedClassifierCV(
        estimator=top_performing_model,
        method=method,
        n_jobs=-1
    ).fit(X_train, y_train)

AttributeError: 'super' object has no attribute '__sklearn_tags__'